"""Collect FastAPI JSON routes and generate .proto + bindings.toml for fgg serve."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Iterator

from fastapi import FastAPI
from fastapi.routing import APIRoute

_UNSUPPORTED = frozenset(
    {"file", "uploadfile", "streamingresponse", "fileresponse", "redirectresponse", "htmlresponse"}
)


@dataclass(frozen=True)
class RouteSpec:
    rpc_name: str
    http_method: str
    path: str
    path_params: tuple[str, ...] = ()
    query_params: tuple[str, ...] = ()
    has_body: bool = False
    summary: str = ""


@dataclass
class SchemaBundle:
    package: str
    service: str
    routes: list[RouteSpec] = field(default_factory=list)
    proto_source: str = ""
    bindings_toml: str = ""


def _pascal(name: str) -> str:
    parts = re.split(r"[^0-9a-zA-Z]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def _rpc_name(route: APIRoute, http_method: str) -> str:
    if route.operation_id:
        return _pascal(route.operation_id)
    base = _pascal(route.name or route.path)
    method = _pascal(http_method.lower())
    if base.lower().startswith(method.lower()):
        return base
    return f"{method}{base}"


def _is_unsupported_route(route: APIRoute) -> bool:
    dep = getattr(route, "dependant", None)
    if dep is None:
        return False
    for param in (
        list(getattr(dep, "body_params", []) or [])
        + list(getattr(dep, "query_params", []) or [])
        + list(getattr(dep, "path_params", []) or [])
    ):
        type_str = str(getattr(param, "type_", "")).lower()
        if any(tok in type_str for tok in _UNSUPPORTED):
            return True
    response_field = getattr(route, "response_field", None)
    if response_field is not None:
        type_str = str(getattr(response_field, "type_", "")).lower()
        if any(tok in type_str for tok in _UNSUPPORTED):
            return True
    return False


def iter_json_routes(app: FastAPI) -> Iterator[RouteSpec]:
    seen: set[str] = set()
    for route in app.routes:
        if not isinstance(route, APIRoute):
            continue
        if _is_unsupported_route(route):
            continue
        methods = sorted(m for m in (route.methods or set()) if m not in {"HEAD", "OPTIONS"})
        for method in methods:
            rpc = _rpc_name(route, method)
            original = rpc
            i = 2
            while rpc in seen:
                rpc = f"{original}{i}"
                i += 1
            seen.add(rpc)

            path_params = tuple(sorted(route.param_convertors.keys()))
            has_body = method in {"POST", "PUT", "PATCH"} or bool(
                getattr(getattr(route, "dependant", None), "body_params", None)
            )
            query_params = tuple(
                sorted(
                    {
                        p.name
                        for p in (getattr(getattr(route, "dependant", None), "query_params", None) or [])
                        if p.name not in path_params
                    }
                )
            )
            yield RouteSpec(
                rpc_name=rpc,
                http_method=method,
                path=route.path,
                path_params=path_params,
                query_params=query_params,
                has_body=has_body,
                summary=(route.summary or route.name or "")[:200],
            )


def render_proto(bundle: SchemaBundle) -> str:
    """All RPCs share RpcRequest; the in-process server maps each RPC to ASGI."""
    lines = [
        'syntax = "proto3";',
        f"package {bundle.package};",
        "",
        f'option go_package = "./{bundle.package};{bundle.package}";',
        "",
        "// Generated by fastapi-grpc-gateway.",
        "// Rust fgg-worker maps each RPC to HTTP for Granian/FastAPI.",
        "",
        "message RpcRequest {",
        "  map<string, string> path = 1;",
        "  map<string, string> query = 2;",
        "  bytes body = 3;",
        "}",
        "",
        "message JsonResponse {",
        "  int32 status_code = 1;",
        "  bytes body = 2;",
        "  map<string, string> headers = 3;",
        "}",
        "",
        f"service {bundle.service} {{",
    ]
    for spec in bundle.routes:
        lines.append(f"  // fgg: {spec.http_method} {spec.path}")
        if spec.summary:
            lines.append(f"  // {spec.summary}")
        lines.append(f"  rpc {spec.rpc_name} (RpcRequest) returns (JsonResponse);")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_bindings(bundle: SchemaBundle) -> str:
    lines = [
        f'package = "{bundle.package}"',
        f'service = "{bundle.service}"',
        "",
    ]
    for spec in bundle.routes:
        lines.append("[[route]]")
        lines.append(f'rpc = "{spec.rpc_name}"')
        lines.append(f'http_method = "{spec.http_method}"')
        lines.append(f'path = "{spec.path}"')
        if spec.path_params:
            inner = ", ".join(f'"{p}"' for p in spec.path_params)
            lines.append(f"path_params = [{inner}]")
        else:
            lines.append("path_params = []")
        if spec.query_params:
            inner = ", ".join(f'"{p}"' for p in spec.query_params)
            lines.append(f"query_params = [{inner}]")
        else:
            lines.append("query_params = []")
        lines.append(f"has_body = {'true' if spec.has_body else 'false'}")
        lines.append("")
    return "\n".join(lines)


def generate_schema(
    app: FastAPI,
    *,
    package: str = "fastapi_grpc",
    service: str = "API",
) -> SchemaBundle:
    routes = list(iter_json_routes(app))
    bundle = SchemaBundle(package=package, service=service, routes=routes)
    bundle.proto_source = render_proto(bundle)
    bundle.bindings_toml = render_bindings(bundle)
    return bundle
