"""Collect FastAPI JSON routes and generate .proto schemas."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Iterator

from fastapi import FastAPI
from fastapi.routing import APIRoute
from fastapi.openapi.utils import get_openapi


_UNSUPPORTED = frozenset(
    {
        "file",
        "uploadfile",
        "streamingresponse",
        "fileresponse",
        "redirectresponse",
        "htmlresponse",
    }
)


@dataclass(frozen=True)
class RouteSpec:
    rpc_name: str
    http_method: str
    path: str
    path_params: tuple[str, ...] = ()
    query_params: tuple[str, ...] = ()
    has_body: bool = False
    summary: str = ""


@dataclass
class SchemaBundle:
    package: str
    service: str
    routes: list[RouteSpec] = field(default_factory=list)
    proto_source: str = ""


def _pascal(name: str) -> str:
    parts = re.split(r"[^0-9a-zA-Z]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def _rpc_name(route: APIRoute, http_method: str) -> str:
    if route.operation_id:
        return _pascal(route.operation_id)
    base = _pascal(route.name or route.path)
    method = _pascal(http_method.lower())
    if base.lower().startswith(method.lower()):
        return base
    return f"{method}{base}"


def _is_unsupported_route(route: APIRoute) -> bool:
    dep = getattr(route, "dependant", None)
    if dep is None:
        return False
    for param in (
        list(getattr(dep, "body_params", []) or [])
        + list(getattr(dep, "query_params", []) or [])
        + list(getattr(dep, "path_params", []) or [])
    ):
        type_str = str(getattr(param, "type_", "")).lower()
        if any(tok in type_str for tok in _UNSUPPORTED):
            return True
    response_field = getattr(route, "response_field", None)
    if response_field is not None:
        type_str = str(getattr(response_field, "type_", "")).lower()
        if any(tok in type_str for tok in _UNSUPPORTED):
            return True
    return False


def iter_json_routes(app: FastAPI) -> Iterator[RouteSpec]:
    """Yield supported JSON APIRoute specs from a FastAPI app."""
    seen: set[str] = set()
    for route in app.routes:
        if not isinstance(route, APIRoute):
            continue
        if _is_unsupported_route(route):
            continue
        methods = sorted(m for m in (route.methods or set()) if m not in {"HEAD", "OPTIONS"})
        for method in methods:
            rpc = _rpc_name(route, method)
            # ensure unique rpc names
            original = rpc
            i = 2
            while rpc in seen:
                rpc = f"{original}{i}"
                i += 1
            seen.add(rpc)

            path_params = tuple(sorted(route.param_convertors.keys()))
            # body: POST/PUT/PATCH typically
            has_body = method in {"POST", "PUT", "PATCH"} or bool(
                getattr(getattr(route, "dependant", None), "body_params", None)
            )
            query_params = tuple(
                sorted(
                    {
                        p.name
                        for p in (getattr(getattr(route, "dependant", None), "query_params", None) or [])
                        if p.name not in path_params
                    }
                )
            )
            yield RouteSpec(
                rpc_name=rpc,
                http_method=method,
                path=route.path,
                path_params=path_params,
                query_params=query_params,
                has_body=has_body,
                summary=(route.summary or route.name or "")[:200],
            )


def _field_lines(names: tuple[str, ...], start: int = 1) -> list[str]:
    lines = []
    for i, name in enumerate(names, start=start):
        # string fields; JSON body is separate bytes
        safe = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        lines.append(f"  string {safe} = {i};")
    return lines


def render_proto(bundle: SchemaBundle) -> str:
    """Render proto3 source for route specs."""
    lines = [
        'syntax = "proto3";',
        f"package {bundle.package};",
        "",
        "// Generated by fastapi-grpc-gateway. Do not edit by hand.",
        "// Each RPC converts to HTTP and is dispatched through the FastAPI ASGI app.",
        "",
        "message JsonResponse {",
        "  int32 status_code = 1;",
        "  bytes body = 2;",
        "  map<string, string> headers = 3;",
        "}",
        "",
    ]

    for spec in bundle.routes:
        msg = f"{spec.rpc_name}Request"
        lines.append(f"// fgg: {spec.http_method} {spec.path}")
        if spec.summary:
            lines.append(f"// {spec.summary}")
        lines.append(f"message {msg} {{")
        n = 1
        for name in spec.path_params:
            safe = re.sub(r"[^a-zA-Z0-9_]", "_", name)
            lines.append(f"  string {safe} = {n};")
            n += 1
        for name in spec.query_params:
            safe = re.sub(r"[^a-zA-Z0-9_]", "_", name)
            lines.append(f"  string {safe} = {n};")
            n += 1
        if spec.has_body:
            lines.append(f"  bytes body = {n};")
        if (
            not spec.path_params
            and not spec.query_params
            and not spec.has_body
        ):
            lines.append("  // empty request")
        lines.append("}")
        lines.append("")

    lines.append(f"service {bundle.service} {{")
    for spec in bundle.routes:
        lines.append(f"  // {spec.http_method} {spec.path}")
        lines.append(
            f"  rpc {spec.rpc_name} ({spec.rpc_name}Request) returns (JsonResponse);"
        )
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_proto(
    app: FastAPI,
    *,
    package: str = "fastapi_grpc",
    service: str = "API",
) -> SchemaBundle:
    """Walk app routes and build a SchemaBundle with proto source."""
    routes = list(iter_json_routes(app))
    bundle = SchemaBundle(package=package, service=service, routes=routes)
    bundle.proto_source = render_proto(bundle)
    return bundle


def openapi_snapshot(app: FastAPI) -> dict[str, Any]:
    """Optional helper: OpenAPI dict used as secondary schema source."""
    return get_openapi(
        title=app.title,
        version=app.version,
        routes=app.routes,
    )
