# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wire.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'wire.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nwire.proto\x12\x08\x66gg.wire\"\xd3\x01\n\nRpcRequest\x12,\n\x04path\x18\x01 \x03(\x0b\x32\x1e.fgg.wire.RpcRequest.PathEntry\x12.\n\x05query\x18\x02 \x03(\x0b\x32\x1f.fgg.wire.RpcRequest.QueryEntry\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x1a+\n\tPathEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a,\n\nQueryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x97\x01\n\x0cJsonResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\x12\x34\n\x07headers\x18\x03 \x03(\x0b\x32#.fgg.wire.JsonResponse.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wire_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RPCREQUEST_PATHENTRY']._loaded_options = None
  _globals['_RPCREQUEST_PATHENTRY']._serialized_options = b'8\001'
  _globals['_RPCREQUEST_QUERYENTRY']._loaded_options = None
  _globals['_RPCREQUEST_QUERYENTRY']._serialized_options = b'8\001'
  _globals['_JSONRESPONSE_HEADERSENTRY']._loaded_options = None
  _globals['_JSONRESPONSE_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_RPCREQUEST']._serialized_start=25
  _globals['_RPCREQUEST']._serialized_end=236
  _globals['_RPCREQUEST_PATHENTRY']._serialized_start=147
  _globals['_RPCREQUEST_PATHENTRY']._serialized_end=190
  _globals['_RPCREQUEST_QUERYENTRY']._serialized_start=192
  _globals['_RPCREQUEST_QUERYENTRY']._serialized_end=236
  _globals['_JSONRESPONSE']._serialized_start=239
  _globals['_JSONRESPONSE']._serialized_end=390
  _globals['_JSONRESPONSE_HEADERSENTRY']._serialized_start=344
  _globals['_JSONRESPONSE_HEADERSENTRY']._serialized_end=390
# @@protoc_insertion_point(module_scope)
